using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace FlowNet.Configuration.CodeAnalysis.SourceGenerators;

[Generator]
public sealed class ConfigPropertyGenerator : IIncrementalGenerator
{
    private const string ConfigPropertyAttribute = "FlowNet.Configuration.ConfigPropertyAttribute";
    private const string StaticConfigPropertyAttribute = "FlowNet.Configuration.StaticConfigPropertyAttribute";

    private sealed class PropertyModel(
        INamedTypeSymbol type,
        IPropertySymbol property,
        string identifier,
        bool isStatic)
    {
        public INamedTypeSymbol Type { get; } = type;
        public IPropertySymbol Property { get; } = property;
        public string Identifier { get; } = identifier;
        public bool IsStatic { get; } = isStatic;
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var instanceProperties = context.SyntaxProvider.ForAttributeWithMetadataName(
                ConfigPropertyAttribute,
                static (node, _) => node is PropertyDeclarationSyntax,
                static (ctx, _) => CreateModel(ctx, false))
            .Where(static model => model != null)
            .Select(static (model, _) => model!);
        var staticProperties = context.SyntaxProvider.ForAttributeWithMetadataName(
                StaticConfigPropertyAttribute,
                static (node, _) => node is PropertyDeclarationSyntax,
                static (ctx, _) => CreateModel(ctx, true))
            .Where(static model => model != null)
            .Select(static (model, _) => model!);

        context.RegisterSourceOutput(instanceProperties.Collect().Combine(staticProperties.Collect()),
            static (spc, properties) => Generate(spc, properties.Left.AddRange(properties.Right)));
    }

    private static PropertyModel? CreateModel(GeneratorAttributeSyntaxContext context, bool isStatic)
    {
        var property = (IPropertySymbol)context.TargetSymbol;
        if (property.IsStatic != isStatic || property.ContainingType is not { } type || !IsPartial(type)) return null;
        if (context.Attributes[0].ConstructorArguments.FirstOrDefault().Value is not string identifier || string.IsNullOrWhiteSpace(identifier)) return null;
        return new PropertyModel(type, property, identifier, isStatic);
    }

    private static bool IsPartial(INamedTypeSymbol type) => type.DeclaringSyntaxReferences
        .Select(reference => reference.GetSyntax())
        .OfType<ClassDeclarationSyntax>()
        .Any(declaration => declaration.Modifiers.Any(modifier => modifier.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword)));

    private static void Generate(SourceProductionContext context, ImmutableArray<PropertyModel> properties)
    {
        foreach (var group in properties.GroupBy(model => model.Type, (IEqualityComparer<INamedTypeSymbol>)SymbolEqualityComparer.Default))
        {
            var type = group.Key;
            var source = new StringBuilder();
            source.AppendLine("// <auto-generated/>");
            source.AppendLine("#nullable enable");
            AppendTypeHeader(source, type, out var indent);
            foreach (var model in group)
            {
                var prefix = new string(' ', indent * 4);
                var property = model.Property;
                var typeName = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                source.Append(prefix).Append("public ");
                if (model.IsStatic) source.Append("static ");
                source.Append("partial ").Append(typeName).Append(' ').Append(property.Name).AppendLine();
                source.Append(prefix).AppendLine("{");
                if (property.GetMethod != null)
                {
                    source.Append(prefix).Append("    get => global::FlowNet.Configuration.ConfigCenter.Get<").Append(typeName);
                    if (model.IsStatic) source.Append(">(\"").Append(Escape(model.Identifier)).Append("\");");
                    else source.Append(", ").Append(type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append(">(\"").Append(Escape(model.Identifier)).Append("\", this);");
                    source.AppendLine();
                }
                if (property.SetMethod != null)
                {
                    source.Append(prefix).Append("    set => global::FlowNet.Configuration.ConfigCenter.Set<").Append(typeName);
                    if (model.IsStatic) source.Append(">(\"").Append(Escape(model.Identifier)).Append("\", value);");
                    else source.Append(", ").Append(type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append(">(\"").Append(Escape(model.Identifier)).Append("\", this, value);");
                    source.AppendLine();
                }
                source.Append(prefix).AppendLine("}");
            }
            while (indent-- > 0) source.Append(' ', indent * 4).AppendLine("}");
            context.AddSource(type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", "") + ".ConfigProperties.g.cs", source.ToString());
        }
    }

    private static void AppendTypeHeader(StringBuilder source, INamedTypeSymbol type, out int indent)
    {
        var namespaceName = type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString();
        indent = 0;
        if (namespaceName != null)
        {
            source.Append("namespace ").Append(namespaceName).AppendLine();
            source.AppendLine("{");
            indent++;
        }
        var chain = new Stack<INamedTypeSymbol>();
        for (var current = type; current != null; current = current.ContainingType) chain.Push(current);
        while (chain.Count > 0)
        {
            var current = chain.Pop();
            source.Append(' ', indent * 4).Append("partial ").Append(GetKind(current)).Append(' ').Append(current.Name);
            if (current.TypeParameters.Length > 0) source.Append('<').Append(string.Join(", ", current.TypeParameters.Select(parameter => parameter.Name))).Append('>');
            source.AppendLine();
            source.Append(' ', indent * 4).AppendLine("{");
            indent++;
        }
    }

    private static string GetKind(INamedTypeSymbol type) => type.IsRecord ? "record" : type.TypeKind == TypeKind.Struct ? "struct" : "class";
    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
